USE harry_sql;

-- CREATION OF FOREIGN KEY TABLE
-- CREATE TABLE address(
-- user_id INT ,
-- street VARCHAR(30) NOT NULL,
-- city VARCHAR(19) NOT NULL,
-- CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(ID) ON DELETE SET NULL
-- );

INSERT INTO address (user_id,street,city)
VALUES
(1,"MG ROAD","NASHIK"),
-- (2,"GANESH COLONY","JALGAON"),
(3,"RAJIV GANDHI BHAVAN","MUMBAI"),
(4,"SUBHASH CHANDRA BOSE ROAD","NAGPUR"),
-- (5,"KADE PATHAR CHOWK","NASHIK"),
(6,"MIDC","JALNA"),
(7,"OMKAR APARTMENT","ALIBAUG"),
(8,"PETH ROAD","SAMBHAJI NAGAR");

SELECT * FROM user;
 SELECT * FROM address; 